pipeline {
    agent any
    stages {
        stage("Clean up"){
            steps {
                deleteDir() //will clear the wokring folder that we are on
            }
        }
        stage("Clone Repo"){
            steps {
                sh "git clone https://github.com/jenkins-docs/simple-java-maven-app.git" //how to clone the git repo 
            }
        }
        stage("Build"){
            steps {
                dir("simple-java-maven-app") {
                    sh "mvn clean install"
                }
            }
        }
        stage("Build Remote"){
            steps {
                Build 'boolPipeline'
            }
        }
    }
}