pipeline{
    agent any
    parameters {
        string(defaultValue: "Test", description: "Which environment to deploy", name: "AZ")
    }
    stages{
        stage("Demo"){
            steps{
                echo "String is set to: ${params.AZ}"
            }
        }
    }
}