pipeline{
    agent any
    parameters{
        string(defaultValue: "Custom deployment name", description: "Deployment name", name: "CD")
        choice(choices: ["EU-WEST-2A", "EU-WEST-2B", "EU-WEST-2C"], description: "Which AZ", name: "AZ name")
        booleanParam(defaultValue: false, description: "Confirm deployment", name: "COnfirmationdeployment")       
    }
    stages{
        stage("Demo"){
            steps{
                echo "Custom deployment name is: ${params.CD}"
                echo "Select deployment: ${AZ name}"
                echo "Confirm deployment status: ${COnfirmationdeployment}"
            }
        }
    }
}